{{ config(
    materialized='table',
    schema='HISTORICAL_SILVER'
) }}

SELECT
    UPPER(TRIM(ICAO24)) AS ICAO24,

    NULLIF(TRIM(REGISTRATION), '') AS REGISTRATION,

    NULLIF(TRIM(AIRCRAFT_TYPE), '') AS AIRCRAFT_TYPE,

    NULLIF(TRIM(DESCRIPTION), '') AS DESCRIPTION,

    NULLIF(TRIM(CALLSIGN), '') AS CALLSIGN,

    "squawk" AS SQUAWK,

    LATITUDE,

    LONGITUDE,

    ALTITUDE_FT,

    ON_GROUND,

    CASE
        WHEN ON_GROUND = 0 THEN FALSE
        WHEN ON_GROUND = 1 THEN TRUE
        ELSE NULL
    END AS ON_GROUND_FLAG,

    CASE
        WHEN ON_GROUND = 0 THEN 'AIRBORNE'
        WHEN ON_GROUND = 1 THEN 'ON GROUND'
        WHEN ON_GROUND IN (2, 3) THEN 'UNKNOWN'
        ELSE 'UNKNOWN'
    END AS ON_GROUND_STATUS,

    EVENT_TIMESTAMP,

    EVENT_DATETIME,

    CAST(EVENT_DATETIME AS DATE) AS EVENT_DATE,

    "event_hour" AS EVENT_HOUR,

    "altitude_band" AS ALTITUDE_BAND,

    SOURCE

FROM {{ source('historical', 'historical_flights') }}

WHERE
    ICAO24 IS NOT NULL
    AND EVENT_DATETIME IS NOT NULL
    AND LATITUDE BETWEEN -90 AND 90
    AND LONGITUDE BETWEEN -180 AND 180