-- =========================================================
-- HISTORICAL FLIGHT DATA — ANALYSIS & QA QUERIES (Snowflake)
-- Run after 03_historical_setup.sql and after dbt has built
-- the silver (STG_HISTORICAL_FLIGHTS) and gold
-- (FACT_AIRCRAFT_POSITIONS / DIM_DATES) models.
-- =========================================================


-- =========================================================
-- 1. Bronze Layer — Basic Checks
-- =========================================================

SELECT *
FROM FLIGHT_DATA.HISTORICAL_BRONZE.HISTORICAL_FLIGHTS
LIMIT 10;

DESC TABLE FLIGHT_DATA.HISTORICAL_BRONZE.HISTORICAL_FLIGHTS;

SELECT
    MIN(EVENT_DATETIME) AS FIRST_EVENT,
    MAX(EVENT_DATETIME) AS LAST_EVENT
FROM FLIGHT_DATA.HISTORICAL_BRONZE.HISTORICAL_FLIGHTS;


-- =========================================================
-- 2. Bronze Layer — Daily Distribution
-- =========================================================

SELECT
    CAST(EVENT_DATETIME AS DATE) AS EVENT_DATE,
    COUNT(*) AS TOTAL_ROWS
FROM FLIGHT_DATA.HISTORICAL_BRONZE.HISTORICAL_FLIGHTS
GROUP BY CAST(EVENT_DATETIME AS DATE)
ORDER BY EVENT_DATE;


-- =========================================================
-- 3. Bronze Layer — Aircraft Counts & Missing Values
-- =========================================================

SELECT
    COUNT(DISTINCT ICAO24) AS UNIQUE_AIRCRAFT
FROM FLIGHT_DATA.HISTORICAL_BRONZE.HISTORICAL_FLIGHTS;

SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT_IF(ICAO24 IS NULL) AS NULL_ICAO24,
    COUNT_IF(EVENT_DATETIME IS NULL) AS NULL_EVENT_DATETIME,
    COUNT_IF(LATITUDE IS NULL) AS NULL_LATITUDE,
    COUNT_IF(LONGITUDE IS NULL) AS NULL_LONGITUDE,
    COUNT_IF(ALTITUDE_FT IS NULL) AS NULL_ALTITUDE
FROM FLIGHT_DATA.HISTORICAL_BRONZE.HISTORICAL_FLIGHTS;

SELECT
    MIN(LATITUDE) AS MIN_LAT,
    MAX(LATITUDE) AS MAX_LAT,
    MIN(LONGITUDE) AS MIN_LON,
    MAX(LONGITUDE) AS MAX_LON
FROM FLIGHT_DATA.HISTORICAL_BRONZE.HISTORICAL_FLIGHTS;


-- =========================================================
-- 4. Bronze Layer — On-Ground & Altitude Breakdown
-- =========================================================

SELECT
    ON_GROUND,
    COUNT(*) AS TOTAL_ROWS
FROM FLIGHT_DATA.HISTORICAL_BRONZE.HISTORICAL_FLIGHTS
GROUP BY ON_GROUND
ORDER BY ON_GROUND;

SELECT
    ALTITUDE_BAND,
    COUNT(*) AS TOTAL_ROWS
FROM FLIGHT_DATA.HISTORICAL_BRONZE.HISTORICAL_FLIGHTS
GROUP BY ALTITUDE_BAND
ORDER BY ALTITUDE_BAND;

SELECT
    MIN(ALTITUDE_FT) AS MIN_ALTITUDE,
    MAX(ALTITUDE_FT) AS MAX_ALTITUDE,
    AVG(ALTITUDE_FT) AS AVG_ALTITUDE
FROM FLIGHT_DATA.HISTORICAL_BRONZE.HISTORICAL_FLIGHTS
WHERE ALTITUDE_FT IS NOT NULL;

SELECT
    ON_GROUND,
    COUNT(*) AS TOTAL_ROWS,
    MIN(LATITUDE) AS MIN_LAT,
    MAX(LATITUDE) AS MAX_LAT,
    MIN(LONGITUDE) AS MIN_LON,
    MAX(LONGITUDE) AS MAX_LON
FROM FLIGHT_DATA.HISTORICAL_BRONZE.HISTORICAL_FLIGHTS
GROUP BY ON_GROUND
ORDER BY ON_GROUND;

-- Spot-check rows with an unexpected ON_GROUND value (only 0/1 expected)
SELECT
    ICAO24,
    REGISTRATION,
    CALLSIGN,
    ON_GROUND,
    LATITUDE,
    LONGITUDE,
    ALTITUDE_FT,
    EVENT_DATETIME
FROM FLIGHT_DATA.HISTORICAL_BRONZE.HISTORICAL_FLIGHTS
WHERE ON_GROUND IN (2, 3)
LIMIT 30;


-- =========================================================
-- 5. Silver Layer (dbt) — QA Checks
-- =========================================================

DESCRIBE TABLE FLIGHT_DATA.dbt_dev_HISTORICAL_SILVER.STG_HISTORICAL_FLIGHTS;

SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DISTINCT ICAO24) AS UNIQUE_AIRCRAFT,
    COUNT(DISTINCT EVENT_DATE) AS DAYS,
    COUNT_IF(ICAO24 IS NULL) AS NULL_ICAO24,
    COUNT_IF(EVENT_DATETIME IS NULL) AS NULL_EVENT_DATETIME,
    COUNT_IF(LATITUDE IS NULL) AS NULL_LATITUDE,
    COUNT_IF(LONGITUDE IS NULL) AS NULL_LONGITUDE,
    COUNT_IF(REGISTRATION IS NULL) AS NULL_REGISTRATION,
    COUNT_IF(CALLSIGN IS NULL) AS NULL_CALLSIGN,
    COUNT_IF(SQUAWK IS NULL) AS NULL_SQUAWK,
    MIN(LATITUDE) AS MIN_LATITUDE,
    MAX(LATITUDE) AS MAX_LATITUDE,
    MIN(LONGITUDE) AS MIN_LONGITUDE,
    MAX(LONGITUDE) AS MAX_LONGITUDE,
    MIN(EVENT_DATETIME) AS FIRST_EVENT,
    MAX(EVENT_DATETIME) AS LAST_EVENT
FROM FLIGHT_DATA.dbt_dev_HISTORICAL_SILVER.STG_HISTORICAL_FLIGHTS;

-- EVENT_DATE consistency check
SELECT COUNT(*) AS WRONG_EVENT_DATE
FROM FLIGHT_DATA.dbt_dev_HISTORICAL_SILVER.STG_HISTORICAL_FLIGHTS
WHERE EVENT_DATE <> CAST(EVENT_DATETIME AS DATE);

-- ICAO24 formatting checks
SELECT COUNT(*) AS LOWERCASE_ICAO24
FROM FLIGHT_DATA.dbt_dev_HISTORICAL_SILVER.STG_HISTORICAL_FLIGHTS
WHERE ICAO24 <> UPPER(ICAO24);

SELECT COUNT(*) AS ICAO24_WITH_SPACES
FROM FLIGHT_DATA.dbt_dev_HISTORICAL_SILVER.STG_HISTORICAL_FLIGHTS
WHERE ICAO24 <> TRIM(ICAO24);

SELECT COUNT(*) AS BAD_ICAO24
FROM FLIGHT_DATA.dbt_dev_HISTORICAL_SILVER.STG_HISTORICAL_FLIGHTS
WHERE ICAO24 <> UPPER(TRIM(ICAO24));

-- ON_GROUND flag/status mapping
SELECT
    ON_GROUND,
    ON_GROUND_FLAG,
    ON_GROUND_STATUS,
    COUNT(*) AS TOTAL_ROWS
FROM FLIGHT_DATA.dbt_dev_HISTORICAL_SILVER.STG_HISTORICAL_FLIGHTS
GROUP BY ON_GROUND, ON_GROUND_FLAG, ON_GROUND_STATUS
ORDER BY ON_GROUND;

-- Altitude band summary
SELECT
    ALTITUDE_BAND,
    COUNT(*) AS TOTAL_ROWS,
    MIN(ALTITUDE_FT) AS MIN_ALTITUDE,
    MAX(ALTITUDE_FT) AS MAX_ALTITUDE
FROM FLIGHT_DATA.dbt_dev_HISTORICAL_SILVER.STG_HISTORICAL_FLIGHTS
GROUP BY ALTITUDE_BAND
ORDER BY ALTITUDE_BAND;

-- Duplicate detection (same aircraft + same timestamp)
SELECT
    ICAO24,
    EVENT_TIMESTAMP,
    COUNT(*) AS DUPLICATE_COUNT
FROM FLIGHT_DATA.dbt_dev_HISTORICAL_SILVER.STG_HISTORICAL_FLIGHTS
GROUP BY ICAO24, EVENT_TIMESTAMP
HAVING COUNT(*) > 1
ORDER BY DUPLICATE_COUNT DESC
LIMIT 20;


-- =========================================================
-- 6. Gold Layer (dbt) — Fact / Dimension Integrity Check
-- =========================================================

-- Fact rows whose DATE_KEY has no matching row in DIM_DATES
SELECT
    f.DATE_KEY,
    COUNT(*) AS ROWS_COUNT
FROM FLIGHT_DATA.DBT_DEV.FACT_AIRCRAFT_POSITIONS f
LEFT JOIN FLIGHT_DATA.DBT_DEV.DIM_DATES d
    ON f.DATE_KEY = d.DATE_KEY
WHERE d.DATE_KEY IS NULL
GROUP BY f.DATE_KEY
ORDER BY f.DATE_KEY;